namespace TimeIsUp {
	enum SpriteSheetRectName {
		Popup = -2,
		None = -1,
		BlockHuge_E,
		BlockLarge_E,
		BlockSmall_E,
		Button_E,
		ButtonPressed_E,
		Floor_E,
		PistolExtended_N,
		PistolExtended_W,
		PistolRetracted_N,
		PistolRetracted_W,
		Portal_N,
		Portal_W,
		SlabQuarter_S,
		WallDoorClosed_N,
		WallDoorClosed_W,
		WallDoorOpen_N,
		WallDoorOpen_W,
		WallDoorway_N,
		WallDoorway_W,
		WallLightOff_N,
		WallLightOff_W,
		WallLightOn_N,
		WallLightOn_W,
		WallStraight_N,
		WallStraight_W,
		WallSwitchOff_N,
		WallSwitchOff_W,
		WallSwitchOn_N,
		WallSwitchOn_W,
		WallWindow_N,
		WallWindow_W,
	}
}